eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: feign
  rabbitmq:
    host: localhost
    port: 5672
    username: geekerit
    password: cnh1k2jJhz
#开启熔断器
feign:
  hystrix:
    enabled: true